name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.x', '16.x']

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.14.1
      - name: install packages
        run: |
          pnpm install
      - name: build
        run: |
          pnpm build
        env:
          CI: true
