name: Lint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.x', '16.x']

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install and build
      run: yarn
      env:
        CI: true

    - name: lint
      run: yarn lint
      env:
        CI: true
